import React, { Component } from "react";
import {
  StyleSheet,
  Text,
  View,
  WebView,
  AppRegistry,
  ScrollView
} from "react-native";
export default class Policy extends Component {
  render() {
    return (
      <ScrollView>
        <View style={styles.content}>
          <Text style={styles.heading1}>Privacy Policy</Text>
          <Text style={styles.prag}>
            Moudak ("us", "we", or "our") operates the Moudak mobile application
            (hereinafter referred to as the "Service"). This page informs you of
            our policies regarding the collection, use, and disclosure of
            personal data when you use our Service and the choices you have
            associated with that data. The Privacy Policy for Moudak has been
            created with the help of TermsFeed. We use your data to provide and
            improve the Service. By using the Service, you agree to the
            collection and use of information in accordance with this policy.
            Unless otherwise defined in this Privacy Policy, the terms used in
            this Privacy Policy have the same meanings as in our Terms and
            Conditions.
          </Text>
          <Text style={styles.heading}>Definitions</Text>
          <Text style={styles.heading2}>Service</Text>
          <Text style={styles.prag}>
            Service is the Moudak mobile application operated by Moudak
          </Text>
          <Text style={styles.heading2}>Personal Data</Text>
          <Text style={styles.prag}>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </Text>
          <Text style={styles.heading2}>Usage Data</Text>
          <Text style={styles.prag}>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </Text>
          <Text style={styles.heading2}>Cookies</Text>
          <Text style={styles.prag}>
            Cookies are small files stored on your device (computer or mobile
            device).
          </Text>
          <Text style={styles.heading}>Information Collection and Use</Text>
          <Text style={styles.prag}>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </Text>
          <Text style={styles.heading2}>Types of Data Collected</Text>
          <Text style={styles.heading2}>Personal Data</Text>
          <Text style={styles.prag}>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you ("Personal Data"). Personally identifiable information
            may include, but is not limited to:
          </Text>
          <Text style={styles.prag}>- Email address</Text>
          <Text style={styles.prag}>- First name and last name</Text>
          <Text style={styles.prag}>- Phone number</Text>
          <Text style={styles.prag}>
            - Address, State, Province, ZIP/Postal code, City
          </Text>
          <Text style={styles.prag}>- Cookies and Usage Data</Text>
          <Text style={styles.heading2}>Usage Data</Text>
          <Text style={styles.prag}>
            When you access the Service by or through a mobile device, we may
            collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile device
            unique ID, the IP address of your mobile device, your mobile
            operating system, the type of mobile Internet browser you use,
            unique device identifiers and other diagnostic data ("Usage Data").
          </Text>
          <Text style={styles.heading2}>Tracking Cookies Data</Text>
          <Text style={styles.prag}>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information. Cookies are
            files with a small amount of data which may include an anonymous
            unique identifier. Cookies are sent to your browser from a website
            and stored on your device. Other tracking technologies are also used
            such as beacons, tags and scripts to collect and track information
            and to improve and analyse our Service. You can instruct your
            browser to refuse all cookies or to indicate when a cookie is being
            sent. However, if you do not accept cookies, you may not be able to
            use some portions of our Service. Examples of Cookies we use:
          </Text>

          <Text style={styles.prag}>
            - Session Cookies. We use Session Cookies to operate our Service.
          </Text>
          <Text style={styles.prag}>
            - Preference Cookies. We use Preference Cookies to remember your
            preferences and various settings.
          </Text>
          <Text style={styles.prag}>
            - Security Cookies. We use Security Cookies for security purposes.
          </Text>
          <Text style={styles.heading}>Use of Data</Text>

          <Text style={styles.prag}>
            Moudak uses the collected data for various purposes:
          </Text>
          <Text style={styles.prag}>- To provide and maintain the Service</Text>

          <Text style={styles.prag}>
            - To notify you about changes to our Service
          </Text>
          <Text style={styles.prag}>
            - To allow you to participate in interactive features of our Service
            when you choose to do so
          </Text>
          <Text style={styles.prag}>
            - To provide customer care and support
          </Text>
          <Text style={styles.prag}>
            - To provide analysis or valuable information so that we can improve
            the Service
          </Text>
          <Text style={styles.prag}>- To monitor the usage of the Service</Text>
          <Text style={styles.prag}>
            - To detect, prevent and address technical issues
          </Text>
          <Text style={styles.heading}>Transfer Of Data</Text>
          <Text style={styles.prag}>
            Your information, including Personal Data, may be transferred to -
            and maintained on - computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ than those from your jurisdiction.
          </Text>
          <Text style={styles.prag}>
            If you are located outside Egypt and choose to provide information
            to us, please note that we transfer the data, including Personal
            Data, to Egypt and process it there.
          </Text>
          <Text style={styles.prag}>
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </Text>
          <Text style={styles.prag}>
            Moudak will take all steps reasonably necessary to ensure that your
            data is treated securely and in accordance with this Privacy Policy
            and no transfer of your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of your data and other personal
            information.
          </Text>
          <Text style={styles.heading}>Disclosure Of Data</Text>
          <Text style={styles.heading2}>Legal Requirements</Text>
          <Text style={styles.prag}>
            Moudak may disclose your Personal Data in the good faith belief that
            such action is necessary to:
          </Text>
          <Text style={styles.prag}>- To comply with a legal obligation</Text>
          <Text style={styles.prag}>
            - To protect and defend the rights or property of Moudak
          </Text>
          <Text style={styles.prag}>
            - To prevent or investigate possible wrongdoing in connection with
            the Service
          </Text>
          <Text style={styles.prag}>
            - To protect the personal safety of users of the Service or the
            public
          </Text>
          <Text style={styles.prag}>- To protect against legal liability</Text>
          <Text style={styles.heading}>Security of Data</Text>
          <Text style={styles.prag}>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </Text>
          <Text style={styles.heading}>Service Providers</Text>
          <Text style={styles.prag}>
            We may employ third party companies and individuals to facilitate
            our Service ("Service Providers"), to provide the Service on our
            behalf, to perform Service-related services or to assist us in
            analyzing how our Service is used.
          </Text>
          <Text style={styles.prag}>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </Text>
          <Text style={styles.heading}>Analytics and Re-marketing</Text>
          <Text style={styles.prag}>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service which means they might collect information used
            to identify you.
          </Text>
          <Text style={styles.prag}>
            Google analytics: visit their Privacy Policy page:
            https://policies.google.com/privacy
          </Text>
          <Text style={styles.prag}>
            Google Adwords: visit their Privacy Policy page:
            https://policies.google.com/privacy
          </Text>
          <Text style={styles.prag}>
            Facebook:visit their Privacy Policy page:
            https://www.facebook.com/policy.php
          </Text>
          <Text style={styles.heading}>Links to Other Sites</Text>
          <Text style={styles.prag}>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party's site. We strongly advise you to review the Privacy
            Policy of every site you visit.
          </Text>
          <Text style={styles.prag}>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </Text>
          <Text style={styles.heading}>Children's Privacy</Text>
          <Text style={styles.prag}>
            Our Service does not address anyone under the age of 18
            ("Children").
          </Text>
          <Text style={styles.prag}>
            We do not knowingly collect personally identifiable information from
            anyone under the age of 18. If you are a parent or guardian and you
            are aware that your Child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from children without verification of parental consent, we take
            steps to remove that information from our servers.
          </Text>
          <Text style={styles.heading}>Changes to This Privacy Policy</Text>
          <Text style={styles.prag}>
            We may update our Privacy Policy from time to time. We will be
            posting the new Privacy Policy on this page.
          </Text>
          <Text style={styles.prag}>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </Text>
          <Text style={styles.heading}>Contact Us</Text>
          <Text style={styles.prag}>
            If you have any questions about this Privacy Policy, please contact
            us:
          </Text>
          <Text style={styles.prag}>By email: info@moudak.com</Text>

          <Text style={styles.heading1}>Terms and Conditions:</Text>
          <Text style={styles.heading}>General Conditions:</Text>
          <Text style={styles.prag}>
            All content contained on this app including but not limited to
            information, data, software, images, graphs, illustrations, maps,
            designs and icons is the intellectual property of Moudak App.
          </Text>
          <Text style={styles.heading}>Trade Mark:</Text>
          <Text style={styles.prag}>
            The Moudak brand and all other trademarks appearing on this app are
            trademarks of Moudak. You may not use, copy, reproduce, publish,
            upload, transmit, transmit, distribute or modify trademarks in any
            form. Including advertising without prior written consent of Moudak.
          </Text>
          <Text style={styles.heading}>User Behaviour:</Text>
          <Text style={styles.prag}>
            You are solely responsible for the content of any materials you
            submit and you agree and warrant that you will not upload, post,
            transmit, distribute or otherwise publish through the App:
          </Text>
          <Text style={styles.prag}>
            - Any illegal materials containing threats, harassment or
            desecration.
          </Text>
          <Text style={styles.prag}>
            - Constitute or encourage conduct that would constitute a crime or
            involve the responsibility of a civilian.
          </Text>
          <Text style={styles.prag}>
            - Any materials containing non - ethical materials.
          </Text>
          <Text style={styles.prag}>
            - Any materials containing viruses or any kind of harmful
            substances.
          </Text>
          <Text style={styles.prag}>- Any false or misleading statements.</Text>
          <Text style={styles.heading}>Restrict Usage:</Text>
          <Text style={styles.prag}>
            - You may only use this app to make legitimate requests concerning
            digital printing. The site may not be used for any fraudulent
            speculation.
          </Text>
          <Text style={styles.prag}>
            - You acknowledge that you are of sufficient legal age to establish
            binding legal obligations for any liability you may incur as a
            result of your use of this site.
          </Text>
          <Text style={styles.prag}>
            - You agree to update the information required for your membership
            (if any) in order to keep your transactions clear, complete and
            accurate.
          </Text>
          <Text style={styles.heading}>Privacy:</Text>
          <Text style={styles.prag}>
            Confirm that you have read, understood and agree to the Privacy
            Policy and agree that it is fair and satisfactory to you and agree
            to the use of your information by Moudak.
          </Text>
          <Text style={styles.heading}>The three parties:</Text>
          <Text style={styles.prag}>
            - If you use this site to provide services or requests for a third
            party or on its behalf you are solely responsible for any error in
            the accuracy of information provided in any request to the company
            and you are solely responsible for the payment of the obligations
            and expenses of this party and you must inform the third party of
            all terms and conditions Which apply to the use of this site
            including all restrictions and rules without exception.
          </Text>
          <Text style={styles.prag}>
            - This agreement constitutes the binding agreement between you and
            Moudak, which may be filed by Moudak at any time and without notice
            at its discretion if you become dissatisfied with the performance of
            the site.
          </Text>
          <Text style={styles.heading}>Changes in Terms and Conditions:</Text>
          <Text style={styles.prag}>
            We may by our sole discretion change, add or remove any part of the
            Terms and Conditions at any time by posting the new Terms on the
            Site.
          </Text>
          <Text style={styles.heading}>Changes to the App:</Text>
          <Text style={styles.prag}>
            We reserve the right for any reason in our sole discretion to
            terminate or change any aspect of the App including but not limited
            to the features provided by the app and we may impose restrictions
            on your access to all or any part of the Site.
          </Text>
        </View>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  content: {
    flex: 1,
    marginBottom: 20
  },
  heading: {
    color: "#54469c",
    fontWeight: 'bold',
    marginLeft: 6,
    paddingTop: 12
  },
  heading1: {
    color: "#54469c",
    fontWeight: 'bold',
    marginLeft: 6,
    paddingTop: 14,
    paddingBottom: 14
  },
  heading2: {
    color: "#000000",
    fontWeight: 'bold',
    marginLeft: 6,
    paddingTop: 4
  },
  prag: {
    marginLeft: 6
  }
});
